### ISSUE TITLE
Node module at NPM

### ISSUE THREAD

**Issue by borekb** [matej21/neon-js#1]
It would be nice to convert this to a Node module and publish it at NPM.

**Comment by matej21** [comment]
I finally published it :) https://www.npmjs.com/package/neon-js

It is my first npm package so I hope everything is ok.

(I will add brief doc later)

**Comment by borekb** [comment]
Thanks! Also the recent README is very welcome, I was a bit struggling with the Map return type. (It may be just me but I'd prefer the `decode()` method to return plain JS object. Right now I need to call `toObject(true)` which is a bit unintuitive. But I understand that there might be a different opinion on this. Thanks for the package anyway!)

**Comment by matej21** [comment]
The problem is, properties in the object are not ordered. I found this in ecmascript 3.0 spec

> An Object is an unordered collection of properties. Each property consists of a name, a value and a set of attributes.

(Neither 5.1 spec nor 6.0 draft mention order of properties in object)

But I have some ideas how to solve this. Probably I will add some decoder...

**Comment by matej21** [comment]
@borekb i'v created PR solving your issue - #2. do you like it?

**Comment by borekb** [comment]
Yes, thanks!

**Comment by matej21** [comment]
merged and 1.1.0 version released
