### ISSUE TITLE
Recursive Map.toObject()

### ISSUE THREAD

**Issue by jesobreira** [matej21/neon-js#6]
Let's say we have this:

```
foo: bar
database:
	driver: mysql
	username: root
	password: beruska92
```

If we do .toObject() to it, we will have:

```
{
"foo": "bar",
"database": Map
}
```

Shouldn't database: also get converted to object? Is there other way to do it recursively?

**Comment by matej21** [comment]
hi, try to call `toObject` method with first parameter set to true

**Comment by jesobreira** [comment]
Thanks, it worked!
